# Generated by Django 4.0.4 on 2022-12-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_pics',
            name='pic',
            field=models.ImageField(upload_to='Profile_pics'),
        ),
    ]
