# Generated by Django 4.0.4 on 2022-12-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRegistrationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.IntegerField()),
                ('Married', models.BooleanField()),
                ('Age', models.IntegerField()),
                ('Date_of_joining', models.DateField()),
                ('Department', models.CharField(choices=[('Sales Department', 'Sales Department'), ('IT Department', 'IT Department'), ('Production Department', 'Production Department')], default='Sales Department', max_length=200)),
            ],
        ),
    ]
