# Generated by Django 4.0.4 on 2022-12-29 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_employeeregistrationmodel_date_of_joining'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeregistrationmodel',
            name='Date_of_joining',
            field=models.DateField(),
        ),
    ]
