# Generated by Django 4.0.4 on 2023-01-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_employeeregistrationmodel_married'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.IntegerField()),
                ('Married', models.CharField(max_length=10)),
                ('Age', models.IntegerField()),
                ('State', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('Date_of_joining', models.DateField()),
                ('Date_of_birth', models.DateField()),
                ('Department', models.CharField(choices=[('Sales Department', 'Sales Department'), ('IT Department', 'IT Department'), ('Production Department', 'Production Department')], default='Sales Department', max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='EmployeeRegistrationModel',
        ),
    ]
